import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { DeviceCategory } from './device-category.enum';

export type DeviceDocument = HydratedDocument<Device>;

@Schema({ collection: 'devices' })
export class Device {
  // Node-generated host-uuid per spec.md's example ("_id": "host-uuid") —
  // assigned by the provisioning CLI, not auto-generated by Mongo.
  @Prop({ type: String, required: true })
  _id!: string;

  @Prop({ required: true, trim: true })
  hostname!: string;

  @Prop({ type: String, required: true, enum: DeviceCategory })
  category!: DeviceCategory;

  // Unknown until the device's first successful ingestion.
  @Prop({ type: { name: String, version: String }, required: false })
  os?: { name: string; version: string };

  // Unset until the device's first successful ingestion.
  @Prop({ required: false })
  lastSeen?: Date;

  // Additive field, not in spec.md's example payload: node authentication.
  // agent.md's dual-auth rule requires a rotable per-node API key (never a
  // shared global key). Same argon2-hash approach as users.passwordHash.
  // Only the argon2 hash of the key's secret half is stored; the plaintext
  // key is issued once by the provisioning/rotation CLI (no REST endpoint
  // for this exists in the authoritative contract) and never persisted.
  @Prop({ required: true })
  apiKeyHash!: string;
}

export const DeviceSchema = SchemaFactory.createForClass(Device);
// Required indexes (agent.md §5.3).
DeviceSchema.index({ category: 1 });
DeviceSchema.index({ 'os.name': 1 });
DeviceSchema.index({ lastSeen: -1 });
